// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using annuaireEntreprise;

namespace annuaireEntreprise.Migrations
{
    [DbContext(typeof(AnnuaireEntreriseContext))]
    [Migration("20220214123925_DbUpdate")]
    partial class DbUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("annuaireEntreprise.DB.Model.Employes", b =>
                {
                    b.Property<int>("Id_employe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_employe")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName_employe")
                        .HasColumnType("TEXT");

                    b.Property<string>("FixeNumber_employe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id_service")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id_site")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName_employe")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber_employe")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceId_service")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiteId_site")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("role_employe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_employe");

                    b.HasIndex("ServiceId_service");

                    b.HasIndex("SiteId_site");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("annuaireEntreprise.DB.Model.Services", b =>
                {
                    b.Property<int>("Id_service")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name_service")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_service");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("annuaireEntreprise.DB.Model.Sites", b =>
                {
                    b.Property<int>("Id_site")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name_site")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_site");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("annuaireEntreprise.DB.Model.Employes", b =>
                {
                    b.HasOne("annuaireEntreprise.DB.Model.Services", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId_service");

                    b.HasOne("annuaireEntreprise.DB.Model.Sites", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId_site");

                    b.Navigation("Service");

                    b.Navigation("Site");
                });
#pragma warning restore 612, 618
        }
    }
}
